### PR TITLE
Update PDF guide

### PR DESCRIPTION
**Pull request by pshevtsov**

### CODE REVIEW

**Comment by jmariomejiap** [comment]
@pshevtsov, were you able to confirm that the `host discovery with Nmap` section was included in the PDF?

**Comment by pshevtsov** [comment]
> @pshevtsov, were you able to confirm that the `host discovery with Nmap` section was included in the PDF?

@jmariomejiap have you added that section to the PDF guide source file?

**Comment by jmariomejiap** [comment]
> > @pshevtsov, were you able to confirm that the `host discovery with Nmap` section was included in the PDF?
> 
> @jmariomejiap have you added that section to the PDF guide source file?

No Petr, I haven’t touched the source file. As we discussed when creating the card, the objective is to regenerate the PDF to include the changes we have been adding to the guides as of late. As an example, one of the items we would like to see in the new PDF is the `host discovery with Nmap` section.
What is included in this new PDF version that is different from the previous one?

**Comment by jmariomejiap** [comment]
I see/saw the difference. The `host discovery with Nmap` section is missing. are you able to add it?

**Comment by pshevtsov** [comment]
@jmariomejiap I've just added that section, PTAL

**Review by jmariomejiap — APPROVED** [review]
Nice, it looks good 🚀 .
Thanks @pshevtsov

**Pull request merged**
