### PR TITLE
Add guide to get all IPs for apps with a tag

### PR DESCRIPTION
**Pull request by prees1**
Adds a guide to get all the IPs for all the servers, that are dependencies for any applications with a given tag.

### CODE REVIEW

**Comment by justinbarclay** [comment]
Can we have a gist for the bash version as well?

**Comment by prees1** [comment]
Yea for sure. It needs two separate 'steps', so two separate gists then or some other way we should do that?

**Comment by justinbarclay** [comment]
Because of the need to get a token? If so could we encapsulate that as a comment?

**Comment by prees1** [comment]
No not the token. That isn't covered here, its linked to the authenticate guide on how to get that. 

The two steps are 'Get the tag' and 'Get the ip addresses'. The first step is separate so that the user can get and confirm the tag ID they are selecting is the one they want to use, before it's queried with.

**Comment by justinbarclay** [comment]
That was my second guess :)

Yeah I splitting them off to two files makes sense to me.

**Comment by prees1** [comment]
Cool, ok will update now.

**Comment by prees1** [comment]
@justinbarclay what do you think? - https://github.com/tidalmigrations/gists/compare/pnr/fetch-ips?expand=1

**Comment by prees1** [comment]
Anything else before merging @justinbarclay ?

**Pull request merged**
